### ISSUE TITLE
I have an error when I try to deorbit 

### ISSUE THREAD

**Issue by lapiante** [giuliodondi/kOS-ShuttleEntrySim#11]
Hello,

I have an issu when I run deorbit.ks. When a hit enter the script try to load and the window pop up but in KOS terminal its happen what you see in screenshot. 

![Capture](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/84133207/c8be837e-1138-40c2-81dd-5f7f66f51319)

I configure my runway near the KSC using your tool.
I use your fork of SSS.
And I follow your instruction in the github.

Can someone tell me what im doing wrong please ?

thank you

**Comment by giuliodondi** [comment]
You are missing a required dependency, specifically you need to install kOS Ferram.
It's one of my own plugins that used to be shipped with the scripts, but now you can find it on CKAN.

Please verify that it's installed

**Comment by lapiante** [comment]
Thank you I just forget to install it. now trying tou get the script work. Thanks for this amazing script

**Comment by giuliodondi** [comment]
That's good to know, if you give me some confirmation that the script works fine now I'll close the issue

**Comment by lapiante** [comment]
I have an other problem with the entry.ks. 
I follow your tuto on YT but when I hit "run entry." I have the error you can see on the screenshot. I try to understand where is the problem but your script is very complex and I don't have the skill to understand it.
thanks for your help.


![Capture](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/84133207/b4213060-3044-4eeb-9340-73f549b48046)

**Comment by giuliodondi** [comment]
You need to switch your KSP language from French to English.
The script needs to actuate some part actions and looks for the English name, and can't find it in this case.

I guess I need to clarify it in the readme since this s the second time someone has this issue

**Comment by lapiante** [comment]
Ok ... Now I understand what the kos windows says. Thank you ... I try and after I confirm you to close the issue.

**Comment by lapiante** [comment]
Perfect Landing to KSC!!!. Thank you so much for your help. You did an amazing job guy. Thank you very much for this scripts.

**Comment by giuliodondi** [comment]
Good to know, thanks!
