### ISSUE TITLE
When I enter the sctipt "run entry" this appears, why does it happen?

### ISSUE THREAD

**Issue by ElMickuy** [giuliodondi/kOS-ShuttleEntrySim#12]
The "run deorbit" script works normally, the problem occurs when I place the "run entry" script in kOS, what is in the image appears. Why does this happen?
What it says about BURAN/ENERGIA was the name I gave to the aircraft
![Captura de pantalla 2023-12-22 205542](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/129906729/3fa5e518-24c8-4552-8122-4dba4c85e92e)

**Comment by giuliodondi** [comment]
your terminal window is wai too small, the erorr message is truncated and I can't know exactly what's wrong.
Make the window very large so that we can read the full message.

But before you do that: the script out of the box is not configured to work with Buran, did you create custom configs or are you using the default configs for my fork of SSS?
Because if it's the latter, then the script will never work without those custom configs, the README does say it

**Comment by ElMickuy** [comment]
OK, This is the message that appears in the kOS terminal.
 I used your fork and don't change anything
![Captura de pantalla 2023-12-23 173734](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/129906729/df0b3fb3-8565-4750-86a2-663bb4400247)

**Comment by giuliodondi** [comment]
Do you use Atmospheric Autopilot? Other people had your same error and we traced it down to an incompatibility with that mod

**Comment by ElMickuy** [comment]
Emm no
Witch mods are incompatible?

**Comment by giuliodondi** [comment]
So far I'm only aware of Atmospheric Autopilot, but there can always be more.

I need more information, so please try this:
- spawn the Shuttle on the runway
- open the kOS terminal, execute the following command:
    **print ship:parts.**
  and post a screenshot with the output.
- execute
    **clearscreen.**
- execute the following command:
    **print ship:partsdubbed("ShuttleTailControl")[0]:modules.**
  and post a second screenshot with the output.
  
  make sure the terminal is quite large as the command output can be loengthy

**Comment by ElMickuy** [comment]
1st scrensshot:
![Captura de pantalla 2023-12-27 193126](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/129906729/b5dc49a4-3e04-4944-9a85-791259dc5bdf)
2nd screenshot:
![Captura de pantalla 2023-12-27 194316](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/129906729/4f1f39a5-54f5-41d5-ba52-505a6dee0fa6)

**Comment by giuliodondi** [comment]
The second screenshot shows the problem: The part is supposed ot have two ModuleControlSurface but yours only has one for some reason.

Please verify that ijndeed you installed the latest SpaceShuttleSuystem from my fork.
Please also verify that you have re-assembled the Orbiter ship from scratch after updating as stated in the SpaceShuttleSystem README.

After you have done both, please re-do this test. If it still doesn't work, we'll have to try a clean KSP install
