### ISSUE TITLE
issue with flapcontrol

### ISSUE THREAD

**Issue by Y0LRIN** [giuliodondi/kOS-ShuttleEntrySim#2]
![image](https://user-images.githubusercontent.com/99510991/153671270-76ab62fd-7c8b-4422-90f0-c5ec31c9167d.png)
I have this error whenever I try to use entry.ks, did I misunderstood something ? How Can I fix ?

**Comment by giuliodondi** [comment]
Hello, sorry for the late reply.

Most likely there is an issue with the craft you're calling the script from.
The kOS script needs to control specific parts (elevons, flaps) and they must be specified in a configuration file, or else the logic is unable to find them and actuate them.
By default the script is configured to use the DECQ shuttle and so there is a folder /VESSELS/DECQ_shuttle containign all the necessary configs. 

It is hard for me to pinpoint the problem without information on what craft you're flying, but if you're trying to fly your own spaceplane you will need to create a brand new folder with config files in the VESSELs directory and then tell the script to use it by changing vessel_dir.ks

**Comment by Y0LRIN** [comment]
Hello, I'm sorry I wasn't very precise. I'm using DECQ shuttle, I didn't change naming neither in the mod files, the RO config files nor your scripts. 
I'm sorry if my grammar is not accurate, english is not my main language

**Comment by giuliodondi** [comment]
The script is configured out of the box to work with the DECQ shuttle version linked in the readme.
The error you are seeing means that the script is looking for all parts named "ShuttleElevonL" and picking the first one, but it cannot find any. This means that whatever DECQ shuttle you are using, there is something wrong with the parts naming.

The way to fix this is to either use a DECQ version that contains the right part names or, as I said, to change the entries in the /VESSELs/DECQ_Shuttle/flapcontrol.ks to reflect the part names that you are actually using
