### ISSUE TITLE
Shuttle loose control during the second bank on reentry

### ISSUE THREAD

**Issue by pgriziotti** [giuliodondi/kOS-ShuttleEntrySim#3]
Hi ,
I'm playing those scripts (that are awesome!). With the shuttle built on SpaceODY parts but during reentry the shuttle loose contol at the second bank maneuver.
I've followed you video on youtube and the instruction for the shuttle configurations on this repository.
Is there something big that I missed? Thanks!

**Comment by giuliodondi** [comment]
Hello, thanks first of all.

I'm sorry but you didn't provide enough information for me to diagnose your problem with certainty.
Are you sure you configured the control surfaces like I explain in the readme? 
Leaving fine controls on during roll reversals is 99% guaranteed to cause a loss of control. Are you sure this isn't your case?
You say the Shuttle could perform the first roll reversal. How did it look like? Was it smooth or did it struggle? Did you see jerky motion, overshooting or the like? Maybe you left SAS on.
Did you have cargo in the Shuttle bay? How much RCS and OMS fuel left? maybe you have some CG balancing issues.

On a side note related to the last point: I did not build and test my script with SpaceODY's Shuttle. Although I believe he uses the RO configs that come standard with RO, there may be some configs that change things like part masses or balancing.
