### ISSUE TITLE
error_main_loop

### ISSUE THREAD

**Issue by Francescocirigliano** [giuliodondi/kOS-ShuttleEntrySim#4]
When run the script entry receive this error and a lot of error relative to gimbal. To finish with error_main_loop.
![error1](https://user-images.githubusercontent.com/66739705/180189681-e9b1e982-9766-4912-85d2-a47c2541c5b3.png)
![error2](https://user-images.githubusercontent.com/66739705/180189706-aa97947a-0b02-4d50-ae9e-ae99e08055dd.png)

How i can solve?

**Comment by giuliodondi** [comment]
It's quite obvious, you need to change your KSP language from Italian to English.

The script will need to actuate things on some parts and it does so by looking for actions with a specific name. Localization messes this up as all actions have a different name

**Comment by Francescocirigliano** [comment]
Yes i fixed change the language. Thanks a lot

**Comment by Arkhamm11** [comment]
about the edit of keybinds that you saw in github tutorial i don't understand how edit. When i try to rebind the pitch axis the game doesn't detect the key. Coulb be maybe is this the problem why i can't turn (only roll works) in the final approch?

**Comment by Francescocirigliano** [comment]
> It's quite obvious, you need to change your KSP language from Italian to English.
> 
> The script will need to actuate things on some parts and it does so by looking for actions with a specific name. Localization messes this up as all actions have a different name

about the edit of keybinds that you saw in github tutorial i don't understand how edit. When i try to rebind the pitch axis the game doesn't detect the key. Coulb be maybe is this the problem why i can't turn (only roll works) in the final approch?

**Comment by giuliodondi** [comment]
The key binding changes are not required by the script, rather they're suggestions to make it easier to fly wth keyboard controls. Maybe I should have made it clearer in the readme.

In any case you definitely need to control all three axis somehow, if you messed up your keyboard bindings just reset them to default, there must be a button somehwere in the settings to do that.

**Comment by Francescocirigliano** [comment]
Yes, I know, but I only have this problem when the script is running. He ran perfectly all up to 20 km after starting the approach the shuttle only goes straight until he crash on the ground.

**Comment by giuliodondi** [comment]
I've never had this problem, to be honest.

The program is meant to give you back full manual control during approach, either if you switch manually or the program switches automatically.  
You say the Shuttle lawn-darts into the ground. But do the elevons move if you hit W-S, do the input indicators on the bottom-left of your screen move?

If they do, then your Shuttle is too nose-heavy to be controlled and you must shift around fuel or payload to ensure that the CG is close to the empty CG.
If they don't it's most likely a problem with your input mappings, so try to fly another airplane and see if you can control it.

The other option is that there's a bug somewhere in the script that locks out control upon switching, but I've never encountered it and, besides, it doesn't make sense given that you say you could control roll.
