### ISSUE TITLE
Error running scripts with SOCK_Shuttle

### ISSUE THREAD

**Issue by bofhgr** [giuliodondi/kOS-ShuttleEntrySim#5]
Hello,

I am having an issue when running the script with the SOCK Shuttle. 

First issue is when running deorbit.ks script, I am providing a screenshot with the error showing up on KOS terminal when I run deorbit.ks.

Second, I also get an error when running the entry.ks script after entering the atmosphere. Attaching another screenshot with that error as well.

I am using the SOCK shuttle in KSP 1.12 from an RP1-Express installation with Principia, using the latest versions provided by CKAN for all mods.

I have edited the file vessel_dir.ks by commenting line 8 and uncommenting line 7 to use the SOCK_Shuttle instead of DECQ_Shuttle_mono

![screenshot1](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/28956359/8383917c-5e7d-42e9-901a-85545382afb9)

![screenshot2](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/28956359/c0a86afa-e694-4c53-b585-ff03002a5931)

Can you please advise?

**Comment by giuliodondi** [comment]
It was my fault, the SOCK vessel configuration was out of date with respect to DECQ because I never use it.
It should be up to date now, I hope it's fixed.

As I said, since I never fly SOCK maybe some parameter here and there needs adjusting, for instance the behaviour of the kOS steering manager seems to have changed between 1.10 and 1.12

**Comment by bofhgr** [comment]
Thank you for the prompt reply!
I can confirm both scripts run, now I'll fine-tune my approach and give you feedback on the SOCK implementation but so far on the first try it seemed really on-point with everything on defaults and no payload return. This looks & feels great! Very promising!

**Comment by giuliodondi** [comment]
glad to hear it! 
do you mind letting me know what were your reentry parameters?
I mean the entry interface data when you run the deorbit predictor

**Comment by bofhgr** [comment]
I didn't remember to take screenshots in the deorbit planner, honestly I didn't expect it to go smoothly on the first try :p I got a couple during re-entry though, not sure if they provide any good information for you.

In my first and only attempt so far, I came from a 250x250 orbit to KSC and after the deorbit burn I had a 55km periapsis just above the KSC with ~5km distance indicated by the deorbit calculator. I don't recall the exact numbers but  It ended up overshooting by a bit having all guidance, brakes and steering on autopilot all the way down. It seems that it pulls minimum deflection on the controls when the shuttle can handle more aggressive turns and breaking. I usually end up close to 20km above KSC with this type of re-entry when I manually land it. It ended up flying like 50k above, which is what the deorbit /burn indicated, having spent minimal RCS to do so. I had too much RCS remaining after the deorbit, close to 250m/s and 7 crewmembers and no payload (plus the weight of airlock/docks). I didn't move any fuel around either.

The entry autopilot ultimately gave an error after overshooting the KSC (didn't quite catch what it said, something about infinity messing it up) and I ended up landing it manually, but even with such an unoptimized reentry it got me to a point where I could easily take control and land it myself. I will try next times with varied re-entries and burns also will play around with the flap settings and deflection, see what works better. What I really liked is that it came down spending only a fraction of RCS, where as in my 'brute force manual deorbits' I tend to waste all my remaining RCS trying to keep it aligned, and that part of the re-entry went really great, so I am quite content with the results so far.

On this note, bundled with the current RP1 installation is Katniss mod for the Cape and I use the shuttle runway it has, I assume when I select KSC it wants to land it there, right? Or should I follow your instructions to enter the coordinates manually for that runway?


![screenshot15](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/28956359/2629b2e0-ef47-4925-ad3c-f7356a6e548a)
![screenshot14](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/28956359/dd8290f3-a0c9-4067-9a37-23583a216eca)
![screenshot13](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/28956359/0b9d2e94-48e1-433e-adce-06dcf824d825)

**Comment by giuliodondi** [comment]
well, overshooting the target at 50k altitude isn't exactly what I would call smooth, I'm not surprised that something in the script exploded.

> "I had a 55km periapsis just above the KSC"

that's far too high energy, at least for the DECQ Shuttle. A more typical trajectory would be periapsis of 10-20 km some distance beyond the target.
That will plunge you deeper into the atmosphere to the point where the Shuttle generates meaningful lift and drag, the descent should almost stop at atound 70 km while the Shuttle is banked and from there aerodynamics does all the work.

The real Space Shuttle often had a negative periapsis because it had so much more L/D at hypersonic speeds compared to what Ferram can calculate given the configs.

>"Or should I follow your instructions to enter the coordinates manually for that runway?"

You should.
it doesn't matter if the KerbalKonstructs static is placed by Katniss or if you place it yourself wherever you want, the final placement can vary a little depending on how the terrain is aligned and formed, especially in elevation.
if the numbers are not right for your in-game situation, the script will also be off and that's to be expected

**Comment by bofhgr** [comment]
So I made my own measurements for the runway, and had time to do a quick test flight. Here is the deorbit calculation
![screenshot36](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/28956359/e05c298d-4543-4812-9f0d-184893a51d3d)
The shuttle had it's fuel moved from the cockpit to the rear before reentry.
I had the control surfaces setup based on the values you had assigned for SOCK in your config files (I think).
I managed to capture a video from the moment the shuttle starts to do some banking maneuver high in the atmosphere and up to the point it blew up due to excessive heating. I hope this is useful for you, I can do more tries with the values you'd like me to use on the control surfaces etc.
https://www.youtube.com/watch?v=eNIsgiPneLU
Also if you can point me to where the flight log file might be located so I can attach it here as well, let me know if you need me to try something more specific or you need any more information.
ps: Unfortunately I don't have much free time this week to do lots of tests, hopefully will be able to manage more time next week to perfect this

**Comment by giuliodondi** [comment]
I see from your image  that you hit Entry interface 4500km from the target, which is far too close. No wonder your predicted reference bank angle is 80°.
The script tries to slow you down in time by forcing a high bank angle so you descend faster, at the cost of a higher heat flux which ultimately kills you. No surprises at all.

I made a quick video on my channel with a reentry test with SOCK for you : https://youtu.be/Alb4x3JBQyY
Also I have this screenshot with my deorbit predictions:
![screenshot25](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/53257302/6dd8f6a9-a897-4c1a-a9dc-1d2104b304bc)

These should show you what the numbers are supposed to be like.
Beware: there are evidently problems with SOCK as it's currently configured as I need to enable infinite fuel at some point and I end up crashing off the runway.

**Comment by bofhgr** [comment]
Thank you for the reply and the comments along the video, these are really helpful! I will make a few more tries hopefully today and get back with more feedback.

I couldn't help but notice that you have 77.000 units of Oxygen in your Cockpit, no wonder why it is so nose heavy for you!!

For my RP1 build (that uses RO_Kerbalism for life support) in my SOCK design, in the Cockpit I have: 4145 units of Oxygen, 25 units of Water, 620 units of Food and 1200 units of Nitrogen. Together with the LH/LOX in the cargo bay this config provides enough life support for 16+ days in orbit and an emergency 1 day of extra supplies once the LH/LOX run out. The remaining space in the Cockpit is for the RCS fuel and the aft fuselage OMS section has only RCS fuel installed.

**Comment by giuliodondi** [comment]
yeah I added some life support stuff by hand with RealFuels because I haven't got kerbalism in my install, I use TAC. 
However, judging by the depletion rates I had like 40 days of supplies, not months or years, so I'm fairly sure that's not why I struggled to maintain balance. 

I also know for a fact that the guy who fixed the RO configs for both SOCK and DECQ balanced them with a full OMS load at the back, I spoke to him on Discord last year.
I told him that's wrong on several levels but apparently no one minds. I don't care since I use my own fork of DECQ anyways

**Comment by bofhgr** [comment]
I get an error now when I run the entry script as you can see in the screenshot. Note that I still have Airbrakes added to the aft fuselage - I have found them useful when flying manual landings without your script, but if you believe I should solely rely on the SOCK vertical stabilizer, I'll give it a try without them as well.

![screenshot50](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/28956359/101d3095-b670-4685-8abc-2a3a93538aa3)

**Comment by giuliodondi** [comment]
sorry I've been quite busy in the last few days,

that error looks weird, looks like there are no aero surface modules on yor rudder part, which makes me think there's something overriding the .cfgs somewhere

anyways the split rudder was an experiment, I also re-made the DECQ russer to behave similarly to the SOCK rudder but they have far too little control authority in addition to drag, plus the script fly-by-wire controller really doesn't like them.
So I think I'll soon revert back to the stock airbrakes

**Comment by bofhgr** [comment]
![image_2023-06-04_024944692](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/28956359/ff2e5163-6b5a-4052-9280-b90d7a9cbda7)
This is the Vertical Stabilizer part in the VAB. I don't believe I have any other mods (besides RO/RP0) that might affect the behavior of this part, so not sure what might be the issue here.

**Comment by giuliodondi** [comment]
that looks good to me, not sure what the isse might be.

anyways now I changed it back to a pair of stock airbrakes for both DECQ and SOCK shuttles, I tested it and it should work like it used to.
Also the airbrake code is designed to throw an error if you forget to put airbrakes on
