### ISSUE TITLE
Error on deorbit prediction.

### ISSUE THREAD

**Issue by AussiePilot123** [giuliodondi/kOS-ShuttleEntrySim#7]
![Screenshot 2023-09-13 213259](https://github.com/giuliodondi/kOS-ShuttleEntrySim/assets/65369842/cfe9877a-b12b-48ff-86b9-154d1893de0d)
This is my first time using this script, and my first time really delving into kOS. I'm trying to do my deorbit prediction, and after creating a rough node and opening the program, this error pops up. I'm probably just being an idiot and doing something wrong, so any help would be appreciated.

**Comment by AussiePilot123** [comment]
Don't worry it seems to have fixed itself😂

**Comment by giuliodondi** [comment]
Sorry, I didn't have time to debug this properly.

The error complains of some equation resulting in 'NaN', which is indicative of a division 0 / 0 in this context.
Based on this I'd say you had your OMS engines turned off when running the script, causing the engine parameters to all be zero.

I still put some of the blame on myself for not putting a check in the script or, at least, clarifying it in the README, so I apologise.
